feat(engine): sync timeout section with zh-docs
leancloud/docs-en pull request #106
Opened 2019-11-22 09:13 UTC by weakish

see also leancloud/docs#3307

2019-11-22 09:14 UTC, leeyeh commented
Deploy preview for *lc-docs-en* ready!

Built with commit c8616f5e6e89a4be8e887b759bff9f55525ed037

https://deploy-preview-106--lc-docs-en.netlify.com

2019-11-25 22:32 UTC, ghost requested changes

2019-11-25 22:32 UTC, shifuchen98 commented on views/leanengine_cloudfunction_guide.tmpl
> +For example, to filter fake comments, one `beforeSave` hook need to call a time-consuming third party NLP API,
need to call -> needs to call

2019-11-26 17:18 UTC, ghost approved these changes

2019-11-26 17:18 UTC, merged