fix(engine): update lean-cli docs
leancloud/docs-en pull request #110
Opened 2019-11-22 11:05 UTC by weakish

1. bump version to 0.21.0
2. describe timezone of lean logs
3. describe how to export logs of one single day

see also leancloud/docs#3322

2019-11-22 11:06 UTC, leeyeh commented
Deploy preview for *lc-docs-en* ready!

Built with commit 5c15ffaeabd1a15a0700a564df14951e592ea19e

https://deploy-preview-110--lc-docs-en.netlify.com

2019-11-25 22:37 UTC, ghost requested changes

2019-11-25 22:37 UTC, shifuchen98 commented on views/leanengine_cli.md
> +`--from` and `--to` uses local timezone (the timezone on the machine executing `lean-cli`).
uses -> use

2019-11-26 17:17 UTC, ghost approved these changes

2019-11-26 17:17 UTC, merged