feat(java): sdk setup with android key
leancloud/docs-en pull request #114
Opened 2019-12-04 07:01 UTC by weakish

see also leancloud/docs#3345

2019-12-04 07:02 UTC, leeyeh commented
Deploy preview for *lc-docs-en* ready!

Built with commit f37fb9911036b3f4a3594a16d5cf36b83d631328

https://deploy-preview-114--lc-docs-en.netlify.com

2019-12-04 16:11 UTC, ghost requested changes

2019-12-04 16:11 UTC, shifuchen98 commented on views/sdk_setup.tmpl
> +Since 6.1.0, we also support [initialize SDK without using appKey](sdk_setup_android_securely.html).
initialize -> initializing

2019-12-04 16:11 UTC, shifuchen98 commented on views/sdk_setup_android_securely.md
> +Since 6.1.0, Leancloud Android SDK supports initialization without appKey,
Leancloud -> LeanCloud

2019-12-04 16:11 UTC, shifuchen98 commented on views/sdk_setup_android_securely.md
> +If your android application will invoke [Cloud Function](leanengine_cloudfunction_guide-node.html),
android -> Android，后面还有一些

2019-12-04 16:11 UTC, shifuchen98 commented on views/sdk_setup_android_securely.md
> +- Python SDK：2.3.0 and later
： -> :

2019-12-04 16:11 UTC, shifuchen98 commented on views/sdk_setup_android_securely.md
> +Probably because you do not add native library to your project.
do -> did

2019-12-04 16:11 UTC, shifuchen98 commented on views/sdk_setup_android_securely.md
> +Probably because your apk does not properly configure signing.
does not properly configure signing -> did not have signing properly configured

2019-12-05 04:26 UTC, ghost approved these changes

2019-12-05 04:26 UTC, merged