realtime_rest_api (WIP)
leancloud/docs-en pull request #142
Opened 2020-01-06 02:26 UTC by lupintheforth

work on realtime_rest_api

2020-01-06 02:27 UTC, leeyeh commented
Deploy preview for *lc-docs-en* ready!

Built with commit f3b8662f1a2e6dfc884b9292e8bff1b1286998c9

https://deploy-preview-142--lc-docs-en.netlify.com

2020-01-17 09:50 UTC, weakish requested changes

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +In table `_Conversation`, the default ACL authority requires master key to create.
authority -> permission 下同

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +The above instance will create an elementary conversation, including two initial participants having client ID 'BillGates' and 'SteveJobs'. A success creation will return the objectId. Namely , the r
elementary -> basic

Namely , the rtm message ID. -> Namely, the conversation ID.

client terminal -> client side 下同

Strings in conversations -> Fields in conversations （下面还有几处把字段翻成 string 的同理）

Realtime Message - guide -> LeanMessage guide

Inputting `"unique": true` -> Passing `"unique": true`

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +return
return -> It returns: 下同

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +limit | optional | together with 'skip' to realize paging
realize -> implement 下同

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +**Warning**, due to the management nature of the interface. When you send meesages via this interface, we will not check whether **from_client**  has the authority to message in the conversation. All
**Warning**, -> **Warning**:

due to ... interface 不是完整的句子，要改成逗号，另外也可以简化一下，比如：since this is an management interface, when you send ...

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +If you used the [Rich Media format](./realtime_v2.html#Message), when sending messages **message** field has some required format, [Rich Media format guide](./realtime_rest_api.html#Rich Media format
If you used -> If you use

when sending messages message field -> the sending message's message field

has some required format, -> has some required format.

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +transient | optional | whether the message is transient, default on FALSE
default on -> default to 下同

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +no_sync | optional | message will get synchronized to the online from_client users, ban this via setting it to TRUE.
ban this via setting it to TRUE -> setting it to TRUE to disable this

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +push_data | optional | set the offline push content of this message as attachment. If receiver is an iOS device and offline, we will push offline content according to this paramter. Refer to [offline
这里要改下（中文文档过时了，很早以前只支持 iOS  设备离线推送，现在 Android 也支持了。中文文档也要改下。）

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +priority | optional | set priority of the message in [high,normal,low]. The parameter is not case-sensitive and default on HIGH. This parameter only works on transient and Chats Rooms messages. Messa
Chats Rooms -> Chat Rooms

Messages are in queue given it has high priority but the connection is blocked. -> High priority messages may still be queued if the connection between server side and client side is blocked.

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +By default , the message API is asynchronous. The Message id and timestamp on Server when received  will get returned. For example: `{"msg-id":"qNkRkFWOeSqP65S9fDyHJw", "timestamp":1495431811151}`.
timestamp on Server when received -> the received timestamp  on the server side

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +To ensure the encapsulation of the chat History, you can use the signature authentication, refer to [Security and Signature](realtime-guide-senior.html#Security and Signature).
encapsulation -> security

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +msgid | Optional | initial message id for query，**It is required to add timestamp as the startpoint of query**
for query， -> for query.

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +till_msgid | Optional | final message id for query **It is required to add till_timestamp as the end of query**
for query -> for query.

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +till_timestamp | Optional | timestamp at end of the query. Default on 0e (on millisecond).
0e -> 0

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +client_id | Optional | viewer id（signature parameter）
这个是中文全角括号，后面还有，需要批量替换成英文括号。

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +This interface has many time parameters. Here we get an instance for your reference. For instance, id1,id2,id3 and the timestamp t1,t2,t3 (t1 < t2 < t3), the different queried result are as follows (
get an instance -> have an example

id1,id2,id3 and the timestamp t1,t2,t3 (t1 < t2 < t3) -> there are three messages (`id1`, `id2`, `id3`) in one conversation, with timestamp `t1`, `t2`, `t3` respectively (`t1 < t2 < t3`)

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +return format, JSON array, sorted on descending timestamp by default, set `reversed` as true to return on reversed order.
return format, JSON array -> It returns a JSON array

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +### One-on-One Chatting/Group Chats-Modify the Messages
`-` 两边加空格

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +From Objective-C SDK v6.0.0、Android SDK v4.4.0、JavaScript SDK v3.5.0 ，we support the new function of modification and recall. After modification and recall, the cached messages on client terminals wi
因为英文文档面向的是新用户，从 `From ...` 开始讲 SDK 兼容性的这几句都可以去掉。

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +> NOTE: this interface will delete the messages on the Server , it does no effect on the client terminal
, it -> . It

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +ttl | prohibited time, seconds , 24h at maximum
`seconds ,` 逗号前多了一个空格

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +---|---|---
这两个参数的描述翻译不完整

2020-01-17 09:50 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +#### Add permanent prohibited user
这里只是禁言，可以翻译成 muted

2020-01-17 09:50 UTC, weakish commented on views/realtime_rest_api.md
> +This interface will return the total number of the online users and the total number of the independent users with logged in history. This interface requires master key.
with logged in history -> logged in today

2020-01-17 09:50 UTC, weakish commented on views/realtime_rest_api.md
> +where | optional | see [Leanstorage - Query](rest_api.html#Query).
rest_api.html#Query -> rest_api.html#Queries

2020-01-17 09:50 UTC, weakish commented on views/realtime_rest_api.md
> +push | Optional | string or JSON | attached push, **all** the iOS and Windows Phone users will receive the notification if sets.
和前面一样，这里中文文档过时了，中文和英文都要改一下，就说手机或者移动端好了
（Android 也支持了，Windows 手机现在没人用了）

2020-01-17 09:50 UTC, weakish commented on views/realtime_rest_api.md
> +Push formats are in align with the `data` part of  [Push Notification REST API message content](push_guide.html#message content_Data). If you need specified developer certificate push, you have to co
in align with -> in alignment with (align 是动词

If you need specified developer certificate push -> If you need to specify the developer push certificate

2020-01-17 09:50 UTC, weakish commented on views/realtime_rest_api.md
> +Parameters and the returned value can refer to [One-on-One Chatting/Group Chats query the history messages](realtime_rest_api.html#query history messages) interface.
... can refor to [...] -> Refer to [...] for ...

2020-01-17 09:50 UTC, weakish commented on views/realtime_rest_api.md
> +The Daily usage is calculated based on all the interfaces. LeanCloud will respond with error code 429 if exceeds the limitation until one minutes later. The interface will reboot after that.
if exceeds the limitation until one minutes later. The interface will reboot after that. -> if exceeding the limit. The REST API will continue to handle requests after one minute. 下同

2020-01-17 09:50 UTC, weakish commented on views/realtime_rest_api.md
> +According to the daily call frequency peak rate , we do differential pricing. As in the following table:
According to the daily call frequency peak rate , we do differential pricing. As in the following table: -> You will be billed for daily request frequency rate peak, as below:

2020-01-17 09:50 UTC, weakish commented on views/realtime_rest_api.md
> +|Daily calling peak rate can be viewed in [Dashboard > Messaging > LeanMessage > API Peak connections][dashboard-rtm-stats].
|Daily -> Daily

2020-01-17 09:51 UTC, weakish commented
还有聊天室、服务号、用户

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_chatroom.njk
> +limit | Optional | together with ski for pagination
ski -> skip

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_chatroom.njk
> +where | Optional | refer to [Leanstorage - Query](rest_api.html#Query).
#Query -> #Queries

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_chatroom.njk
> +### Query the count of online users
Query the Count of Online Users

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_chatroom.njk
> +### Get the online users Randomly
Get the Online Users Randomly

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_chatroom.njk
> +return:
这三行可删。

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_chatroom.njk
> +### One-on-One Chatting/Group Chats - Recall the Messages
One-on-One Chatting/Group Chats -> Chatrooms

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_chatroom.njk
> +返回
It returns:

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_chatroom.njk
> +返回
It returns:

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_system.njk
> +## Official Accounts and bots
bots -> Bots

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_system.njk
> +where | Optional | refer to [Leanstorage - Query](rest_api.html#Query).
[Leanstorage - Query](rest_api.html#Query) -> [LeanStorage - Query](rest_api.html#Queries)

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_system.njk
> +### Traverse through all the subscribers - Query
Traverse through all the subscribers - Query -> Traverse Through All the Subscribers

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_system.njk
> +timestamp is the time of subscription. Subscriber is client_id. If the query is not exhaustive, the last client_id should be retrieved for the next query.
timestamp is the time of subscription. Subscriber is client_id. If the query is not exhaustive, the last client_id should be retrieved for the next query. ->

`timestamp` is the time of subscription, and `subscriber` is the `client_id`. If the query is not exhaustive, the last client_id in the results should be passed as the `client_id` parameter of the next query.

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_system.njk
> +### Query the count of the subscribers
Count the Subscribers

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_system.njk
> +### Message all the subscribers
Message All the Subscribers 后面还有一些标题也需要改成 titlecase，或者整篇文档标题都统一用首字母大写，其他一律小写的形式也行

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_system.njk
> +return
此行可删

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_client.njk
> +client_ids | required | queried client ID list, 20 at most
queried client ID list, 20 at most -> clients to query, at most 20

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_client.njk
> +conv_id | optional | conversation ID, query all the unread message by the client in all the conversations.
query all the unread message ... -> if not specified, query all the unread messages ...

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_client.njk
> +### Forced Offline
Forced Offline  -> Force Offline

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_client.njk
> +### Query the subscribed Official Account
Query Official Accounts Subscribed

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_client.njk
> +timestamp | optional | integer | query the timestamp of the subscription. **Always** use with conv_id, value should be matched to timestamp of the conversation specified by conv_id, unit on milisecon
**Always** use with conv_id, value should be matched to timestamp of the conversation specified by conv_id, unit on milisecond ->

If you have specified the `conv_id` parameter, you must also specify this parameter and its value should match the time of the conversation specified by `conv_id`. Its unit is millisecond.

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_client.njk
> +limit | optional | integer | returned number limit, default on 50.
returned -> return

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_client.njk
> +Invoke this interface can query messages sent by specified client_id in One-on-One Chatting/Group Chats and Chats Room.
Chats Room -> Chatrooms

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_chatroom.njk
> +## Chats Rooms
Chats Rooms -> Chat Rooms 下同

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_client.njk
> +parameters and the returned value refer to [One-on-One Chatting/Group Chats query the history messages](realtime_rest_api.html#Query history messages) interface.
For parameters and the returned value, you can refer to ...

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_client.njk
> +One client is permitted to add one group chat/ chatroom / Official Account to the Blocked list. Then no other clients is prohibited from joining in the conversations.
Then no other clients is prohibited from joining in the conversations. -> Then this client cannot be added to these blocked conversations by other clients.

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_client.njk
> +Currently client cannot add another client into the Blocked List.
Currently client -> Currently one client

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_client.njk
> +### Remove Blocked List
Remove from Blocked List

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_client.njk
> +This interface allows app using [AV.User](rest_api.html#User-1) expressly realize sign-in authentication. Sign-in authentication is closed by default, go to [Dashboard > Messaging > LeanMessage > Set
rest_api.html#User-1 -> rest_api.html#Users

中文文档这里的链接也是坏的，也需要修正下

expressly realize sign-in authentication -> to implement sign-in authentication quickly

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_client.njk
> +To facilitate the Fine-grained control for users, realizing functions self-customized (Blocked List), this interface provides hook function `_rtmClientSign`. After Verifying the sessionToken to invok
Fine -> fine

provides hook function -> provides a hook function

After Verifying the sessionToken to invoke, -> This hook will be invoked after verifying the sessionToken.

the input parameter is JSON object comprised of AV.User. -> Its parameter is a JSON object of `AV.User`.

2020-01-21 10:07 UTC, weakish commented on views/_rtm_rest_api_client.njk
> +Two types of results may receive:
You may receive two types of results:

2020-01-22 07:29 UTC, lupintheforth commented on views/_rtm_rest_api_normal.njk
> +---|---|---
那么这里的所有中文文档也要修改一下吧？

2020-01-22 07:49 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +---|---|---
我的意思只是这里漏翻了（limit 的描述「together with」后面没有了，next 的描述还是中文没翻译

2020-01-22 08:49 UTC, weakish approved these changes

2020-01-22 08:49 UTC, weakish commented on views/_rtm_rest_api_client.njk
> +## User
User 后面多了一个空格

2020-01-22 08:49 UTC, weakish commented on views/_rtm_rest_api_client.njk
> +### Query Count of unread Messages
unread -> Unread

2020-01-22 08:49 UTC, weakish commented on views/_rtm_rest_api_normal.njk
> +next | Optional | returned on the first query, the following query with this parameter to implement pagination
the following query with this parameter to implement pagination -> and the following query will use this parameter to implement pagination

2020-01-22 09:15 UTC, weakish commented
因为这个 pr 比较久了，而且目前 rest rtm 指南并没有入口，所以现在先合并了，以防留着逐渐会和 master 冲突。unresolved conversation 我会另提一个 pr。

2020-01-22 09:15 UTC, merged