fix(objc, java): add `unique: true` for LeanMessage
leancloud/docs-en pull request #41
Opened 2019-02-25 10:54 UTC by weakish

2019-02-25 10:54 UTC, leeyeh commented
Deploy preview for *lc-docs-en* ready!

Built with commit 42dc39e9b8250dacce3d77b0ae1dfcaffb7ca0a1

https://deploy-preview-41--lc-docs-en.netlify.com

2019-02-25 14:58 UTC, ghost requested changes

2019-02-25 14:58 UTC, fuchenshi commented on views/realtime_guide.tmpl
> +                    // 发送消息
这部分代码的消息和注释可以用英文。

2019-02-25 15:21 UTC, leeyeh commented on views/realtime_guide.tmpl
> +    AVIMClient tom = AVIMClient.getInstance("Tom");
https://github.com/leancloud/docs/issues/2624#issuecomment-422236849

2019-02-26 02:07 UTC, ghost approved these changes

2019-02-26 02:11 UTC, merged