feat(rtm): add code sample for custom msg attr
leancloud/docs-en pull request #86
Opened 2019-10-16 10:07 UTC by weakish

see also leancloud/docs#3274

2019-10-16 10:08 UTC, leeyeh commented
Deploy preview for *lc-docs-en* ready!

Built with commit 9d60cd7b631e896667089a6e2e68b84313b8bd0a

https://deploy-preview-86--lc-docs-en.netlify.com

2019-10-16 18:16 UTC, ghost requested changes

2019-10-16 18:16 UTC, shifuchen98 commented on views/realtime-guide-intermediate.md
> +When composing messages with these types, you can include additional information by attaching custom attributes in the format of key-value pairs. For example, if your are sending an message and need
an message > a message

2019-10-16 18:16 UTC, shifuchen98 commented on views/realtime-guide-intermediate.md
> +Therefore, we suggest that you create your own message types only when
only when... ?

2019-10-17 03:18 UTC, ghost approved these changes

2019-10-17 03:19 UTC, merged